version: '3'

services:
  veyltech-app:
    build:
      context: ..
      dockerfile: tools/Dockerfile
    container_name: veyltech-app
    restart: always
    ports:
      - "1818:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ../public:/app/public
    networks:
      - veyltech-network

networks:
  veyltech-network:
    driver: bridge 